package com.MonitoramentoVeicular.enum_;

public enum TipoAlerta {
	VELOCIDADE_ALTA, 
	VELOCIADADE_MODERADA,
	VELOCIDADE_BAIXA,
	CONSUMO_ALTO,
	CONSUMO_MODERADO,
	CONSUMO_BAIXO,
	COMBUSTIVEL_ALTO,
	COMBUSTIVEL_MODERADO,
	COMBUSTIVEL_BAIXO

}
